baseURL = "https://jiyuutsubasa.tk/"
languageCode = "zh-CN"
title = "德小窗"
theme = "ink-free"
paginate = 5

copyright = "© 德先生的小窗"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "民主使每个人成为自己的主宰"

	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	featherIconsCDN = true

	# Enable a table of contents
	toc = true

	# Max tags
  	maxTags = 7

  # Define words per minute to approximate reading time
  wpm = 250

	# Stupid footers :)
	footers = [ 
		"关于 x86 汇编，Tiger King 能教给我们什么",
		"应该用 JavaScript 重写 gcc 的 10 个原因 - 你不会相信 #8！"
	]

	# Github base url
  	github = "https://github.com/weemint/jiyuutsubasa"


# Nav.
[[menu.main]]
name = "主页"
url = "/"
weight = 1

[[menu.main]]
name = "帖子"
url = "/posts"
weight = 2

[[menu.main]]
name = "标签"
url = "/tags"
weight = 3

[[menu.main]]
name = "关于"
url = "/about"
weight = 4

[[params.social]]
name = "RSS订阅"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
